server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mint_store?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: "041104"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      format-sql: true
wx:
  appid: wxcd2a517da90ce81f
  secret: 31869c96988b67bb81aa5710e4b93f26
  code2session: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code
jwt:
  secret: mint-store
  expired: 86400000